server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: zxy20020221
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-idle: 20
        max-active: 50


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
